support typealias
lunarway/SwaggerSwift pull request #104
Opened 2022-06-21 12:41 UTC by mxsc

This is a temporary hack, will fix the solution in SwaggerSwiftML. It is legal to define this in Swagger:

```yaml
definitions:
...
  MyDefintion:
    type: String
    format: MyFormat
```

which unless you add code to specifically handle the format a plain string. Since type aliases are potentially dangerous especially with generic name for these definitions like `Amount`, I think it is better to just resort to the primitive type for these objects where they are used.

2022-06-21 12:43 UTC, MadsBogeskov commented
@mxsc please add a test for this case so that we don't break it in the future.

2022-06-22 09:53 UTC, MadsBogeskov requested changes

2022-06-22 10:01 UTC, mxsc commented on Sources/SwaggerSwiftCore/API Factory/APIFactory.swift
> +    }
```suggestion
```

2022-06-24 07:50 UTC, MadsBogeskov approved these changes

2022-06-24 07:52 UTC, merged