allow refs in addtional property
lunarway/SwaggerSwift pull request #80
Opened 2022-03-17 11:18 UTC by mxsc

2022-03-17 11:29 UTC, MadsBogeskov requested changes

2022-03-17 11:29 UTC, MadsBogeskov commented on Sources/SwaggerSwiftCore/Functions/getType.swift
> +            return (.en)
What is this?

2022-03-18 07:18 UTC, mxsc commented on Sources/SwaggerSwiftCore/Functions/getType.swift
> +            return (.en)
somehow I managed to commit something useless. returning a string now.

2022-03-21 08:47 UTC, mxsc commented on Sources/SwaggerSwiftCore/Functions/getType.swift
> +            return (.string,[])
```suggestion
            return (.string, [])
```

2022-03-22 18:59 UTC, MadsBogeskov approved these changes

2022-03-22 18:59 UTC, merged